spring:
  application:
    name: ai-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
  datasource:
    password: E628L1..3K220
    url: jdbc:mysql://124.70.111.229:3306/aiagent?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wfh.aiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8080
  servlet:
    context-path: /api